apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    service-type: node-port
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80