apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-albport
  labels:
    app : albnode-port
    environment: albroboshopnode
spec:
  containers:
    - name: nginx-nodeport
      image: nginx
      ports:
        - containerPort: 80