apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-nodeport
  labels:
    service-type: node-port
    project: roboshop
spec:
  containers:
    - name: nginx-nodeport
      image: nginx
      ports:
        - containerPort: 80