apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-nodeport
  labels:
    app : node-port
    environment: roboshopnode
spec:
  containers:
    - name: nginx-nodeport
      image: nginx
      ports:
        - containerPort: 80