apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app : node-port
    demo : roboshopnode
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


