apiVersion: v1
kind: Pod
metadata:
  name: cluster-ip-service-pod
  labels:
    app: nginx
    project : H2o-roboshop
spec:
  containers:
    - name: nginx-service
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: env.config.map
