apiVersion: v1
kind: Service
metadata:
  name: albnodeport-service
spec:
  type: NodePort
  selector:
    app: albnode-port
    environment: albroboshopnode
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  