apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: LoadBalancer
  selector:
    app : albnode-port
    environment: albroboshopnode
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


