apiVersion: v1
kind: Pod
metadata:
  name: refconfig-pod
  labels:
    project: roboshop
    componets: catalogue
spec:
  containers:
    - name: refconfig-pod
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: env.config.map 
    