apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels:
    app: web
    project: roboshop
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      project: roboshop
      tier: frontend
  template:
    metadata:
      labels:
        app: web
        project: roboshop
        tier: frontend
    spec:
      containers:
        - name: web
          image: harinadhareddy/web:1.0.0
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    app: web
    project: roboshop
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

