apiVersion: v1
kind: Pod
metadata:
  name: pod-annotations
  namespace: roboshop
  annotations:
    env: "production"
    app: "nginx"
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
