apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
- name: roboshop-node-gp
  spot: true
  instanceType: m5.large
  desiredCapacity: 3
