apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        app: redis
        project: roboshop
        tier: database
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    app: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379


