apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        app: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mongodb
        image: harinadhareddy/mongodb:1.0.0
        imagePullyPolice: always

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    app: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

