apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql_config
  namespace: roboshop
data:
  MYSQL_DATAB ASE: "cities"

---

apiVersion: v1
kind: Secret
metadata:
  name: secret_config
  namespace: roboshop
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQo=
  MYSQL_USER: c2hpcHBpbmcK
  MYSQL_PASSWORD: Um9ib1Nob3BAMQo=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      project: roboshop
      tier: db 
  template:
    metadata:
      labels:
        app: mysql
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mysql_db
        image: harinadhareddy/mysql:1.0.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mysql_config
        - secretRef:
            name: secret_config

---
apiVersion: v1
kind: Service
metadata:
  name: mysql_service
  namespace: roboshop
spec:
  selector:
    app: mysql
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306